name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Scoop
        shell: pwsh
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $env:GITHUB_PATH
      - name: Install mangabinder from this bucket
        shell: pwsh
        run: |
          scoop bucket add preygle $PWD
          scoop install preygle/mangabinder
          mangabinder --version
          mangabinder --help
